on:
  push:
    branches:
      - fix/Docker
  workflow_dispatch:
  
jobs:
  run_pull:
    name: Deploy and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Connect, Pull, and Build Docker
      run: |
        ssh -o StrictHostKeyChecking=no admin@pog.threemusketeer.click << EOF
          set -e
          cd /home/admin/Documents/roomify/roomify-fe
          git stash || true  # Ignore errors if there are no stashed changes
          git pull origin deploy/develop
          cd /home/admin/Documents/roomify
          echo "${{ secrets.SSH_PASS }}" | sudo -S docker compose up frontend --build -d
        EOF